name: ${APP_NAME}_${NODE_ENV}
services:
  app:
    container_name: ${APP_NAME}.${NODE_ENV}
    image: ${APP_NAME}.${NODE_ENV}:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: ${NODE_ENV}
      args:
        - NODE_ENV=${NODE_ENV}
        - APP_PORT=${APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=${APP_PORT}
    networks:
      - traefik-net
      - default
    labels:
      traefik.enable: true
      traefik.http.routers.${APP_NAME}.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.${APP_NAME}.entrypoints: websecure
      traefik.http.routers.${APP_NAME}.tls: true
      traefik.http.routers.${APP_NAME}.tls.certresolver: myresolver
      traefik.http.services.${APP_NAME}.loadbalancer.server.port: ${APP_PORT}
networks:
  traefik-net:
    external: true
