name: ${PROJECT_NAME}_${NODE_ENV}
services:
  app:
    container_name: ${PROJECT_NAME}.${NODE_ENV}
    image: ${PROJECT_NAME}.${NODE_ENV}:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=${APP_PORT}
    networks:
      - traefik-net
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=${APP_PORT}"
networks:
  traefik-net:
    external: true
